# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (every day 2:30AM)
  schedule: [{cron: "30 2 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          #  - repo
          # The following additional scopes may be required:
          #  - read:org  (for organization related metrics)
          #  - read:user (for user related data)
          #  - repo      (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: avaleriani
          template: classic
          base: header, activity, community, repositories, metadata
          config_octicon: yes
          config_timezone: Europe/Berlin
          config_twemoji: yes
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: D
          plugin_discussions: yes
          plugin_discussions_categories: yes
          plugin_gists: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 40
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 360
          plugin_languages_recent_load: 500
          plugin_languages_sections: most-used
          plugin_lines: yes
          plugin_music_mode: top
          plugin_music_provider: spotify
          plugin_music_token: ${{ secrets.METRICS_SPOTIFY_TOKEN }}
          plugin_music_time_range: short
          plugin_music_top_type: tracks
          plugin_pagespeed: yes
          plugin_pagespeed_screenshot: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_token: ${{ secrets.METRICS_PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://agustinvaleriani.com
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: ${{ secrets.METRICS_STACKOVERFLOW_USERID }}
          plugin_stackoverflow_limit: 2
          plugin_stackoverflow_lines: 2
          plugin_stackoverflow_lines_snippet: 2
          plugin_stackoverflow_sections: answers-top
          plugin_stars: yes
          plugin_stars_limit: 3
          plugin_traffic: yes
          repositories: 800
          repositories_forks: yes
          plugin_habits: yes
          plugin_habits_from: 800
          plugin_habits_days: 30
          plugin_habits_facts: yes

